language: generic

dist: trusty

script:
  - docker build -t ws-tls-scanner .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: develop
    script: >-
      docker tag ws-tls-scanner siwecos/ws-tls-scanner:develop &&
      docker push siwecos/ws-tls-scanner:develop
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: >-
      docker tag ws-tls-scanner siwecos/ws-tls-scanner:latest &&
      docker push siwecos/ws-tls-scanner:latest
  - provider: script
    skip_cleanup: true
    on:
      tags: true
    script: >-
      docker tag ws-tls-scanner siwecos/ws-tls-scanner:$TRAVIS_TAG &&
      docker push siwecos/ws-tls-scanner:$TRAVIS_TAG
